config/routes.rb
D3::Application.routes.draw do
  resources :charts

end

app/models/chart.rb
class Chart < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  # GET /charts
  # GET /charts.json
  def index
 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/views/charts/_form.html.erb
<%= form_for(@chart) do |f| %>
  <% if @chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% @chart.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/charts/circles.html.erb
 <script type="text/javascript">
 
		// define dimensions of graph
		var m = [80, 80, 80, 80]; // margins
		var w = 1000 - m[1] - m[3]; // width
		var h = 400 - m[0] - m[2]; // height

 var questions = [];
        $.each(stats.questions, function(index, value) {
          questions.push([value.question, value.time * 10,  80]);
        });

       
	// var questions = [
	// 						[5, 20], [480, 90], [250, 50], [100, 33], [330, 95],
	// 						[410, 12], [475, 44], [25, 67], [85, 21], [220, 88]
	// 					  ];
	
 console.log(questions);
			//Create SVG element
			var svg = d3.select("body")
						.append("svg")
						.attr("width", w)
						.attr("height", h);

			svg.selectAll("circle")
			   .data(questions)
			   .enter()
			   .append("circle")
			   .attr("cx", function(d) {
			   		return d[1];
			   })
			   .attr("cy", function(d) {
			   		return d[2];
			   })
			   .attr("r", 5);












</script>


app/views/charts/edit.html.erb
<h1>Editing chart</h1>

<%= render 'form' %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

app/views/charts/final.html.erb
<meta charset="utf-8">
<style>

body {
  font: 10px sans-serif;
}

.axis path, .axis line {
  fill: none;
  stroke: #000;
  shape-rendering: crispEdges;
}

.area {
  fill: black;
}

.line {
  fill: none;
  stroke: steelblue;
  stroke-width: 1.5px;
}

.dot {
  fill: white;
  stroke: steelblue;
  stroke-width: 1.5px;
}

</style>
<body>
<script src="../../d3.v2.js"></script>
<script>

var data = d3.range(40).map(function(i) {
  return {x: i / 39, y: (Math.sin(i / 3) + 2) / 4};
});

var margin = {top: 10, right: 10, bottom: 20, left: 40},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

var x = d3.scale.linear()
    .domain([0, 1])
    .range([0, width]);

var y = d3.scale.linear()
    .domain([0, 1])
    .range([height, 0]);

var xAxis = d3.svg.axis()
    .scale(x)
    .orient("bottom");

var yAxis = d3.svg.axis()
    .scale(y)
    .orient("left");

var line = d3.svg.line()
    .x(function(d) { return x(d.x); })
    .y(function(d) { return y(d.y); });

var area = d3.svg.area()
    .x(line.x())
    .y1(line.y())
    .y0(y(0));

var svg = d3.select("body").append("svg")
    .datum(data)
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

svg.append("path")
    .attr("class", "area")
    .attr("d", area);

svg.append("g")
    .attr("class", "x axis")
    .attr("transform", "translate(0," + height + ")")
    .call(xAxis);

svg.append("g")
    .attr("class", "y axis")
    .call(yAxis);

svg.append("path")
    .attr("class", "line")
    .attr("d", line);

svg.selectAll(".dot")
    .data(data.filter(function(d) { return d.y; }))
  .enter().append("circle")
    .attr("class", "dot")
    .attr("cx", line.x())
    .attr("cy", line.y())
    .attr("r", 3.5);

</script>

app/views/charts/index.html.erb
<style type="text/css">
/* No style rules here yet */   
</style>
<style>
/* tell the SVG path to be a thin blue line without any area fill */
path {
  stroke: steelblue;
  stroke-width: 1;
  fill: none;
}

triangle {
  stroke: steelblue;
  stroke-width: 1;
  fill: none;
} 

.axis {
  shape-rendering: crispEdges;
}

.x.axis line {
  stroke: lightgrey;
}

.x.axis .minor {
  stroke-opacity: .5;
}

.x.axis line, .x.axis path {
  fill: none;
  stroke: #000;
}

.y.axis line, .y.axis path {
  fill: none;
  stroke: #000;
}
</style>

<body>


  <div id="graph" class="aGraph" style="position:absolute;top:0px;left:0; float:left;"></div>


  <script>
  /* implementation heavily influenced by http://bl.ocks.org/1166403 */

    // define dimensions of graph
    var m = [80, 80, 80, 80]; // margins
    var w = 1000 - m[1] - m[3]; // width
    var h = 400 - m[0] - m[2]; // height

    // create a simple comprehension array that we'll plot with a line (this array represents only the Y values, X will just be the index location)
    $(document).ready(function() {

      //pull all comprehension instances into an array  
      var comprehension = [];
      $.each(stats.huh, function(index, value) {
        comprehension.push(value.time);
      });

      //pull all comprehension instances into an array
      var ahas = [];
      $.each(stats.aha, function(index, value) {
        (ahas.push(parseInt(value.time)));
      });


      
        //create a function to measure the total time of the video
        function arrayLength(value, length) {
          var arr = [], i = length;
          while (i--) {
            arr[i] = value;
          }
          return arr;
        };

      //setup array to handle aggregate values
      var comprehension_count = arrayLength(stats.viewers, stats.duration);
      var aha_count = arrayLength(0, stats.duration);

        //convert all intances into aggregate values
        $.each(comprehension, function(index, value) {
          comprehension_count[value-1]--;
        });

        $.each(ahas, function(index, value) {
          aha_count[value-1]++;
        });



      //convert aggregate values into a percentage
      var comprehension_percentage = [];
      $.each(comprehension_count, function(index, value) {
        comprehension_percentage.push(value / stats.viewers * 100);
      });


      var questions = [];
      $.each(stats.questions, function(index, value) {
        questions.push([value.question, value.time,  comprehension_percentage[value.time - 1]]);
      });

      console.log(ahas);
      console.log(aha_count);
      console.log(comprehension);
      console.log(comprehension_count);
      console.log(comprehension_percentage);
      console.log(questions)



    // X scale will fit all values from comprehension_percentage[] within pixels 0-w
    var x = d3.scale.linear().domain([0, comprehension_percentage.length]).range([0, w]);
    // Y scale will fit values from 0-10 within pixels h-0 (Note the inverted domain for the y-scale: bigger is up!)
    var y = d3.scale.linear().domain([0, 100]).range([h, 50]);
      // automatically determining max range can work something like this
      // var y = d3.scale.linear().domain([0, d3.max(comprehension_percentage)]).range([h, 0]);

    // create a line function that can convert comprehension_percentage[] into x and y points
    var line = d3.svg.line()
      // assign the X function to plot our line as we wish
      .x(function(d,i) { 
        // verbose logging to show what's actually being done
        console.log('Plotting X value for comprehension_percentage point: ' + d + ' using index: ' + i + ' to be at: ' + x(i) + ' using our xScale.');
        // return the X coordinate where we want to plot this comprehension_percentagepoint
        return x(i); 
      })
      .y(function(d) { 
        // verbose logging to show what's actually being done
        console.log('Plotting Y value for comprehension_percentage point: ' + d + ' to be at: ' + y(d) + " using our yScale.");
        // return the Y coordinate where we want to plot this comprehension_percentagepoint
        return y(d);
      })


      // Add an SVG element with the desired dimensions and margin.
      var graph = d3.select("#graph").append("svg:svg")
      .attr("width", w + m[1] + m[3])
      .attr("height", h + m[0] + m[2])
      .append("svg:g")
      .attr("transform", "translate(" + m[3] + "," + m[0] + ")");

      
      // Add the x-axis.
      var xAxis = d3.svg.axis().scale(x).tickValues([comprehension_percentage.length]).orient("bottom");
      graph.append("svg:g")
      .attr("class", "x axis")
      .attr("transform", "translate(-25," + (h) + ")")
      .call(xAxis);

      // Add axis on top of graph
      var topAxis = d3.svg.axis().scale(x).tickValues("","");
      graph.append("svg:g")
      .attr("class", "x axis")
      .attr("transform", "translate(-25, 45)")
      .call(topAxis);




      // create left yAxis
      var yAxisLeft = d3.svg.axis().scale(y).tickValues([50, 100]).orient("left");
      // Add the y-axis to the left
      graph.append("svg:g")
      .attr("class", "y axis")
      .attr("transform", "translate(-25,0)")
      .call(yAxisLeft);



        // Add the line by appending an svg:path element with the comprehension_percentage line we created above
      // do this AFTER the axes above so that the line is above the tick-lines
      graph.append("svg:path").attr("d", line(comprehension_percentage));
      console.log('outputting contents of graph variable')
      console.log(graph);


        //show question circles
        var circle = graph.selectAll("circle")
        .data(questions)
        .enter()
        .append("circle")
        .attr("cx", function(d) {
          return x(d[1]-1);
        })
        .attr("cy", function(d) {
          return y(d[2]);
        })
        .attr("r", 3)
        .on("mouseover", mouse_over)
        .on("mouseout", mouse_out );


        // graph.append("svg:path").data(ahas).attr("d", d3.svg.symbol().type("triangle-up"));

      triangle = graph.selectAll(".point")
        .data(ahas)
        .enter().append("path")
        .attr("class", "point")
        .attr("d", d3.svg.symbol().type("triangle-down").size(500))
        .attr("transform", function(d) { return "translate(" + x(d) + "," + 30 + ")"; })
        .text("hello");
        
        // ADD AHA COUNT CODE HERE
        // ADD AHA COUNT CODE HERE
        // ADD AHA COUNT CODE HERE
        // ADD AHA COUNT CODE HERE


        function mouse_over(e){
          var color_change =d3.select(this).style("fill", "blue");
          var blurb = e[0];
          
          $("#blurb-content").html(blurb);
        };

        function mouse_out(){

          var reset = d3.select(this).style("fill", "black");
          
          $("#blurb-content").html('');
        };






      });



</script>
<div id="blurb">
  
  <div id="blurb-content"></div>
</div>

app/views/charts/line_chart.html.erb


		<style>
			/* tell the SVG path to be a thin blue line without any area fill */
			path {
				stroke: steelblue;
				stroke-width: 1;
				fill: none;
			}

			.axis {
			  shape-rendering: crispEdges;
			}

			.x.axis line {
			  stroke: lightgrey;
			}

			.x.axis .minor {
			  stroke-opacity: .5;
			}

			.x.axis path {
			  display: none;
			}

			.y.axis line, .y.axis path {
			  fill: none;
			  stroke: #000;
			}
		</style>

	<body>


	<div id="graph" class="aGraph" style="position:absolute;top:0px;left:0; float:left;"></div>


	<script>
		/* implementation heavily influenced by http://bl.ocks.org/1166403 */

		// define dimensions of graph
		var m = [10, 10, 10, 10]; // margins
		var w = 600 ; // width
		var h = 300 ; // height
		

		// create a simple data array that we'll plot with a line (this array represents only the Y values, X will just be the index location)
		var data = [3, 6, 2, 7, 5, 2, 0, 3, 8, 9, 2, 5, 9, 3, 6, 3, 6, 2, 7, 5, 2, 1, 3, 8, 9, 2, 5, 9, 2, 7];
		var dataset = [
							[5, 5], [480, 90], [250, 50], [100, 33], [330, 95],
							[410, 12], [475, 44], [25, 67], [85, 21], [220, 88]
						  ]
	

			//Create scale functions
			
			var x = d3.scale.linear().domain([0, data.length]).range([0, w]);

			var y = d3.scale.linear().domain([0, 10]).range([h, 0]);
			

			

		// X scale will fit all values from data[] within pixels 0-w
	
		// Y scale will fit values from 0-10 within pixels h-0 (Note the inverted domain for the y-scale: bigger is up!)
	
			// automatically determining max range can work something like this
			// var y = d3.scale.linear().domain([0, d3.max(data)]).range([h, 0]);

		// create a line function that can convert data[] into x and y points
		var line = d3.svg.line()
			// assign the X function to plot our line as we wish
			.x(function(d,i) { 
				// verbose logging to show what's actually being done
				console.log('Plotting X value for data point: ' + d + ' using index: ' + i + ' to be at: ' + x(i) + ' using our xScale.');
				// return the X coordinate where we want to plot this datapoint
				return x(i+1); 
			})
			.y(function(d) { 
				// verbose logging to show what's actually being done
				console.log('Plotting Y value for data point: ' + d + ' to be at: ' + y(d) + " using our yScale.");
				// return the Y coordinate where we want to plot this datapoint
				return y(d); 
			})

			// Add an SVG element with the desired dimensions and margin.
			var graph = d3.select("#graph").append("svg:svg")
			      .attr("width", w + m[1] + m[3])
			      .attr("height", h + m[0] + m[2])
			    .append("svg:g")
			      .attr("transform", "translate(" + m[3] + "," + m[0] + ")");

			// create yAxis
			var xAxis = d3.svg.axis().scale(x).tickSize(-h).tickSubdivide(true);
			// Add the x-axis.
			graph.append("svg:g")
			      .attr("class", "x axis")
			      .attr("transform", "translate(0," + h + ")")
			      .call(xAxis);


			// create left yAxis
			var yAxisLeft = d3.svg.axis().scale(y).ticks(4).orient("left");
			// Add the y-axis to the left
			graph.append("svg:g")
			      .attr("class", "y axis")
			      .attr("transform", "translate(0,0)")
			      .call(yAxisLeft);

  			// Add the line by appending an svg:path element with the data line we created above
			// do this AFTER the axes above so that the line is above the tick-lines
  			graph.append("svg:path").attr("d", line(data));

  			graph.selectAll("circle")
			   .data(dataset)
			   .enter()
			   .append("circle")
			   .attr("cx", function(d) {
			   		return x(d[0]);
			   })
			   .attr("cy", function(d) {
			   		return y(d[1]);
			   })
			   .attr("r", 4);



	</script>

app/views/charts/mousing.html.erb
<html>
<head>
    <script type="text/javascript" ></script>
</head>
<body>
    <div id="viz"></div>
    <script type="text/javascript">
var dataset = [
                         [5, 20]
                       ];
    var sampleSVG = d3.select("#viz")
        .append("svg")
        .attr("width", 100)
        .attr("height", 100);    

    sampleSVG.selectAll("circle")
    .data(dataset)
    .enter().append("circle")
    .style("stroke", "gray")
    .style("fill", "white")
    .attr("r", 40)
    .attr("cx", function(d, i){return i*80+40})
    .attr("cy", 50)
    .on("mouseover", function(){d3.select(this).style("fill", "aliceblue");})
    .on("mouseout", function(){d3.select(this).style("fill", "white");})
    .on("mouseover", animateFirstStep);

function animateFirstStep(){
    d3.select(this)
      .transition()
        .delay(0)
        .duration(1000)
        .attr("r", 10)
        .each("end", animateSecondStep);
};

function animateSecondStep(){
    d3.select(this)
      .transition()
        .duration(1000)
        .attr("r", 40);
};
    
    </script>
</body>
</html>


app/views/charts/new.html.erb
<style type="text/css">
/* No style rules here yet */		
</style>
<style>
/* tell the SVG path to be a thin blue line without any area fill */
path {
	stroke: #0071BC;
	stroke-width: 5;
	fill: #B5E5F7;
}

.area {
  fill: black;
}

.axis {
	shape-rendering: crispEdges;
}

.x.axis line {
	stroke: lightgrey;
}

.x.axis .minor {
	stroke-opacity: .5;
  stroke-width: 1;
}

.x.axis line, .x.axis path {
	fill: none;
	stroke: #000;
  stroke-width: 1;
}

.y.axis line, .y.axis path {
	fill: none;
	stroke: #000;
  stroke-width: 1;
}
</style>

<body>


	<div id="graph" class="aGraph" style="position:absolute;top:0px;left:0; float:left;"></div>


	<script>
	/* implementation heavily influenced by http://bl.ocks.org/1166403 */

		// define dimensions of graph
		var m = [80, 80, 80, 80]; // margins
		var w = 1000 - m[1] - m[3]; // width
		var h = 400 - m[0] - m[2]; // height

		// create a simple comprehension array that we'll plot with a line (this array represents only the Y values, X will just be the index location)
		$(document).ready(function() {

    	//pull all comprehension instances into an array  
    	var comprehension = [];
    	$.each(stats.huh, function(index, value) {
    		comprehension.push(value.time);
    	});

      //pull all comprehension instances into an array
      var ahas = [];
      $.each(stats.aha, function(index, value) {
      	(ahas.push(parseInt(value.time)));
      });


      
        //create a function to measure the total time of the video
        function arrayLength(value, length) {
        	var arr = [], i = length;
        	while (i--) {
        		arr[i] = value;
        	}
        	return arr;
        };

	    //setup array to handle aggregate values
	    var comprehension_count = arrayLength(stats.viewers, stats.duration);
	    var aha_count = arrayLength(0, stats.duration);

        //convert all intances into aggregate values
        $.each(comprehension, function(index, value) {
        	comprehension_count[value-1]--;
        });

        $.each(ahas, function(index, value) {
        	aha_count[value-1]++;
        });



    	//convert aggregate values into a percentage
    	var comprehension_percentage = [];
    	$.each(comprehension_count, function(index, value) {
    		comprehension_percentage.push(value / stats.viewers * 100);
    	});


    	var questions = [];
    	$.each(stats.questions, function(index, value) {
    		questions.push([value.question, value.time,  comprehension_percentage[value.time - 1]]);
    	});

    	console.log(ahas);
    	console.log(aha_count);
    	console.log(comprehension);
    	console.log(comprehension_count);
    	console.log(comprehension_percentage);
    	console.log(questions)



		// X scale will fit all values from comprehension_percentage[] within pixels 0-w
		var x = d3.scale.linear().domain([0, comprehension_percentage.length]).range([0, w]);
		// Y scale will fit values from 0-10 within pixels h-0 (Note the inverted domain for the y-scale: bigger is up!)
		var y = d3.scale.linear().domain([0, 100]).range([h, 50]);
			// automatically determining max range can work something like this
			// var y = d3.scale.linear().domain([0, d3.max(comprehension_percentage)]).range([h, 0]);

		// create a line function that can convert comprehension_percentage[] into x and y points
		var line = d3.svg.line()
			// assign the X function to plot our line as we wish
			.x(function(d,i) { 
				// verbose logging to show what's actually being done
				console.log('Plotting X value for comprehension_percentage point: ' + d + ' using index: ' + i + ' to be at: ' + x(i) + ' using our xScale.');
				// return the X coordinate where we want to plot this comprehension_percentagepoint
				return x(i); 
			})
			.y(function(d) { 
				// verbose logging to show what's actually being done
				console.log('Plotting Y value for comprehension_percentage point: ' + d + ' to be at: ' + y(d) + " using our yScale.");
				// return the Y coordinate where we want to plot this comprehension_percentagepoint
				return y(d);
			})



			// Add an SVG element with the desired dimensions and margin.
			var graph = d3.select("#graph").append("svg:svg")
			.attr("width", w + m[1] + m[3])
			.attr("height", h + m[0] + m[2])
			.append("svg:g")
			.attr("transform", "translate(" + m[3] + "," + m[0] + ")");

			
			// Add the x-axis.
			var xAxis = d3.svg.axis().scale(x).tickValues([comprehension_percentage.length]).orient("bottom");
			graph.append("svg:g")
			.attr("class", "x axis")
			.attr("transform", "translate(-25," + (h) + ")")
			.call(xAxis);

			// Add axis on top of graph
			var topAxis = d3.svg.axis().scale(x).tickValues("","");
			graph.append("svg:g")
			.attr("class", "x axis")
			.attr("transform", "translate(-25, 45)")
			.call(topAxis);




			// create left yAxis
			var yAxisLeft = d3.svg.axis().scale(y).tickValues([50, 100]).orient("left");
			// Add the y-axis to the left
			graph.append("svg:g")
			.attr("class", "y axis")
			.attr("transform", "translate(-25,0)")
			.call(yAxisLeft);



  			// Add the line by appending an svg:path element with the comprehension_percentage line we created above
			// do this AFTER the axes above so that the line is above the tick-lines
			graph.append("svg:path").attr("d", line(comprehension_percentage))
    


			console.log('outputting contents of graph variable')
			console.log(graph);


  			//show question circles
  			var circle = graph.selectAll("circle")
  			.data(questions)
  			.enter()
  			.append("circle")
  			.attr("cx", function(d) {
  				return x(d[1]-1);
  			})
  			.attr("cy", function(d) {
  				return y(d[2]);
  			})
  			.attr("r", 3)
  			.on("mouseover", mouse_over)
  			.on("mouseout", mouse_out );


  			// graph.append("svg:path").data(ahas).attr("d", d3.svg.symbol().type("triangle-up"));

  		triangle = graph.selectAll(".triangle")
  			.data(ahas)
  			.enter().append("path")
  			// .attr("class", "point")
  			.attr("d", d3.svg.symbol().type("triangle-down").size(500))
  			.attr("transform", function(d) { return "translate(" + x(d) + "," + 30 + ")"; })
  			.text("hello");
  			

  			$(function() {

  				$('.point').mouseover(function(){

  					$(".point").append('10');
  			});
});
  			

  			function mouse_over(e){
  				var color_change =d3.select(this).style("fill", "blue");
  				var blurb = e[0];
  				
  				$("#blurb-content").html(blurb);
  			};

  			function mouse_out(){

  				var reset = d3.select(this).style("fill", "black");
  				
  				$("#blurb-content").html('');
  			};






  		});



</script>
<div id="blurb">
	
	<div id="blurb-content"></div>
</div>

app/views/charts/scatter.html.erb
<style type="text/css">
			
			.axis path,
			.axis line {
				fill: none;
				stroke: black;
				shape-rendering: crispEdges;
			}
			
			.axis text {
				font-family: sans-serif;
				font-size: 11px;
			}

		</style>

<script type="text/javascript">

			//Width and height
			//Width and height
			var w = 500;
			var h = 300;
			var padding = 30;
			
			/*
			//Static dataset
			var dataset = [
							[5, 20], [480, 90], [250, 50], [100, 33], [330, 95],
							[410, 12], [475, 44], [25, 67], [85, 21], [220, 88],
							[600, 150]
						  ];
			*/
			
			//Dynamic, random dataset
			var dataset = [];					//Initialize empty array
			var numDataPoints = 50;				//Number of dummy data points to create
			var xRange = Math.random() * 1000;	//Max range of new x values
			var yRange = Math.random() * 1000;	//Max range of new y values
			for (var i = 0; i < numDataPoints; i++) {					//Loop numDataPoints times
				var newNumber1 = Math.round(Math.random() * xRange);	//New random integer
				var newNumber2 = Math.round(Math.random() * yRange);	//New random integer
				dataset.push([newNumber1, newNumber2]);					//Add new number to array
			}

			//Create scale functions
			var xScale = d3.scale.linear()
								 .domain([0, d3.max(dataset, function(d) { return d[0]; })])
								 .range([padding, w - padding * 2]);

			var yScale = d3.scale.linear()
								 .domain([0, d3.max(dataset, function(d) { return d[1]; })])
								 .range([h - padding, padding]);

			var rScale = d3.scale.linear()
								 .domain([0, d3.max(dataset, function(d) { return d[1]; })])
								 .range([2, 5]);

			//Define X axis
			var xAxis = d3.svg.axis()
							  .scale(xScale)
							  .orient("bottom")
							  .ticks(5);

			//Define Y axis
			var yAxis = d3.svg.axis()
							  .scale(yScale)
							  .orient("left")
							  .ticks(5);

			//Create SVG element
			var svg = d3.select("body")
						.append("svg")
						.attr("width", w)
						.attr("height", h);

			//Create circles
			svg.selectAll("circle")
			   .data(dataset)
			   .enter()
			   .append("circle")
			   .attr("cx", function(d) {
			   		return xScale(d[0]);
			   })
			   .attr("cy", function(d) {
			   		return yScale(d[1]);
			   })
			   .attr("r", function(d) {
			   		return rScale(d[1]);
			   });

			/*
			//Create labels
			svg.selectAll("text")
			   .data(dataset)
			   .enter()
			   .append("text")
			   .text(function(d) {
			   		return d[0] + "," + d[1];
			   })
			   .attr("x", function(d) {
			   		return xScale(d[0]);
			   })
			   .attr("y", function(d) {
			   		return yScale(d[1]);
			   })
			   .attr("font-family", "sans-serif")
			   .attr("font-size", "11px")
			   .attr("fill", "red");
		  	*/
			
			//Create X axis
			svg.append("g")
				.attr("class", "axis")
				.attr("transform", "translate(0," + (h - padding) + ")")
				.call(xAxis);
			
			//Create Y axis
			svg.append("g")
				.attr("class", "axis")
				.attr("transform", "translate(" + padding + ",0)")
				.call(yAxis);
		</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D3</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>